import { Column, Row } from '@/DataGrid';

export const columns: Column<Row>[] = [
  {
    key: 'id',
    name: 'ID',
    width: 80,
    resizable: true,
    frozen: true,
  },
  {
    key: 'avatar',
    name: 'Avatar',
    width: 80,
    resizable: true,
    renderer: 'image',
  },
  {
    key: 'title',
    name: 'Title',
    width: 200,
    resizable: true,
    editable: true,
    renderer: 'select',
  },
  {
    key: 'firstName',
    name: 'First Name',
    width: 200,
    resizable: true,
    frozen: true,
    editable: true,
  },
  {
    key: 'lastName',
    name: 'Last Name',
    width: 200,
    resizable: true,
    frozen: true,
    editable: true,
  },
  {
    key: 'email',
    name: 'Email',
    width: 'max-content',
    resizable: true,
    editable: true,
  },
  {
    key: 'street',
    name: 'Street',
    width: 200,
    resizable: true,
    editable: true,
  },
  {
    key: 'zipCode',
    name: 'ZipCode',
    width: 200,
    resizable: true,
    editable: true,
  },
  {
    key: 'date',
    name: 'Date',
    width: 200,
    resizable: true,
    editable: true,
  },
  {
    key: 'bs',
    name: 'bs',
    width: 200,
    resizable: true,
    editable: true,
  },
  {
    key: 'catchPhrase',
    name: 'Catch Phrase',
    width: 'max-content',
    resizable: true,
    editable: true,
  },
  {
    key: 'companyName',
    name: 'Company Name',
    width: 200,
    resizable: true,
    editable: true,
  },
  {
    key: 'sentence',
    name: 'Sentence',
    width: 'max-content',
    resizable: true,
    editable: true,
  },
];
